### ISSUE TITLE
LED color behavior on Android

### ISSUE THREAD

**Issue by thorathome** [blynkkk/beta#183]
Hi Blynk.  
I am running on iOS (iPad) and on Android (Google Pixel 3a XL + Android 11). 

LED widgets on iOS are working well now. Android still having problems with "color".  

Using `Blynk.setProperty` with "color" works on iOS, not on my Android. 
With Android, it appears that I need to manually set the LED color at the mobile app for it to respond to the 
`Blynk.setProperty ( ..., "color"` ... commands. 
Once the LED color is manually reset at the app, the LED responds to the `Blynk.setProperty `command as expected. 
Exiting Blynk on the mobile app and returning sometimes allows the LEDs to misbehave again.  

I am using `Blynk.virtualWrite`, not `WidgetLED`. 

Hope this is helpful. 
iOS
![iOS](https://user-images.githubusercontent.com/2821513/125499826-64ba1efa-88ee-4cee-b15a-64cb93ff62d6.png)

Android
![Android](https://user-images.githubusercontent.com/2821513/125499854-64a812cc-b0ab-42da-8d1a-a7df7b7d5713.png)

**Comment by alexkipar** [comment]
@thorathome can you provide examples of color values sent to the led, maybe it is smth connected to their format

**Comment by thorathome** [comment]
Yes. 
The screenshots you saw use
- "color" = "#23C48E" `Blynk.setProperty ( Vx, "color", "#23C48E" ); `
- value = 150 or 0  `Blynk.virtualWrite ( Vx, 150 ); `or `Blynk.virtualWrite ( Vx, 150 ); `
- datastream min/max of 0/255

LED widget "color" works as expected on iOS 14.6 on iPad, not on Android 11. 

FYI, the `setProperty ... "label" `functions appears to work on both iOS and Android.

**Comment by alexkipar** [comment]
@thorathome it seems we fixed the issue on our side, I suppose we will upload a new version tomorrow or the day after tomorrow

**Comment by thorathome** [comment]
I am pleased and impressed with the constant progress, will watch for a new Android app. 
Thanks.

**Comment by alexkipar** [comment]
@thorathome, a new build with a fix to this issue should be available soon to update

**Comment by thorathome** [comment]
Hi Blynk team.
We're almost there with this fix. I find the Blynk LED widgets work well under iOS (iPad), still have a problem on Android.

Android 11
Google Pixel 3a XL
- and - 
Android 9 (latest version for this model phone)
Samsung Note8
 
In order for the Android LEDs to work, I have to MANUALLY open the LED widget on the Android device in developer mode and change the LED color from the default. Once that color is reset, the LED works on multiple Androids and stays working. Until I open that widget up and change the color, it does not.  These LED widgets were initially set up on an iOS device. I tend to use them with a value of 0 or 150, with Datastream Min/Max of 0/255. 

Hope this is helpful.

**Comment by thorathome** [comment]
But wait, there's more. I am seeing the same behavior on other Android Blynk widgets where they work well on iOS. 

**The LED, Text Input, and Icon Button widgets all show the same behavior.**.. their colors, as assigned by `Blynk.setProperty( Vx, "color", ...)` commands, do not change UNLESS the widget's color has been manually reset once at the mobile app. Once the widget's color has been set MANUALLY, the `Blynk.setProperty `calls work as expected.  

This is true with the latest `BlynkSimpleEsp32_SSL.h` and `BlynkSimpleEsp8266_SSL.h` libraries, latest Android Blynk mobile apps, and updated Android operating systems. iOS works fine.

**Comment by alexkipar** [comment]
@thorathome Icon Button does not support same color change logic: it uses onColor, offColor properties

**Comment by alexkipar** [comment]
@thorathome, can you send logs after reproducing this issue? We have problems reproducing it on our side.
